services:
  # Base de Datos
  db:
    image: mysql:8.0
    container_name: travelai-db
    restart: always
    environment:
      MYSQL_DATABASE: travelai
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: travelai
      MYSQL_PASSWORD: Travelai1234?
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql_data:/var/lib/mysql
    networks:
      - travelai-net
    healthcheck:
      test:
        ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Backend [Laravel]
  app:
    build:
      context: .
      dockerfile: docker/php.Dockerfile
    container_name: travelai-app
    volumes:
      - ./backend:/var/www
    depends_on:
      - db
    networks:
      - travelai-net

  # Nginx
  nginx:
    image: nginx:alpine
    container_name: travelai-nginx
    ports:
      - "8082:80"
    volumes:
      - ./backend:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - travelai-net

  # phpMyAdmin
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: travelai-phpmyadmin
    ports:
      - "8083:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    networks:
      - travelai-net

  # Frontend [React]
  frontend:
    build:
      context: .
      dockerfile: docker/frontend.Dockerfile
    container_name: travelai-frontend
    ports:
      - "8081:8080"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - travelai-net

networks:
  travelai-net:
    driver: bridge
