services:
  # Base de Datos [MySQL]
  db:
    image: mysql:8.0
    container_name: travelai-db
    restart: always
    environment:
      MYSQL_DATABASE: travelai
      MYSQL_ROOT_PASSWORD: rootTravelai1234
      MYSQL_USER: travelai
      MYSQL_PASSWORD: Travelai1234?
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql_data:/var/lib/mysql
    networks:
      - travelai-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 20s

  # Backend [Laravel]
  app:
    build:
      context: .
      dockerfile: docker/php.Dockerfile
    container_name: travelai-app
    restart: always
    volumes:
      - ./backend:/var/www
    depends_on:
      db:
        condition: service_healthy
    networks:
      - travelai-net

  # Servidor Web [Nginx - 8082]
  nginx:
    image: nginx:alpine
    container_name: travelai-nginx
    restart: always
    ports:
      - "8082:80"
    volumes:
      - ./backend:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - travelai-net

  # phpMyAdmin [8083]
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: travelai-phpmyadmin
    restart: always
    ports:
      - "8083:80"
    environment:
      - PMA_HOST=db
      - MYSQL_ROOT_PASSWORD=rootTravelai1234
    depends_on:
      - db
    networks:
      - travelai-net

  # Frontend [React - 8081]
  frontend:
    image: node:22-alpine
    container_name: travelai-frontend
    working_dir: /app
    ports:
      - "8081:8080"
    environment:
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./frontend:/app
    networks:
      - travelai-net
    # Forzar a Vite a escuchar en el 8080 interno y abrirse al exterior con --host
    command: sh -c "npm install && npm run dev -- --port 8080 --host"

networks:
  travelai-net:
    driver: bridge
